export const REQUEST_ARRIVAL_INFO = 'REQUEST_ARRIVAL_INFO'
export const REQUEST_DEPARTURE_INFO = 'REQUEST_DEPARTURE_INFO'
export const RECEIVE_ARRIVAL_INFO = 'RECEIVE_ARRIVAL_INFO'
export const RECEIVE_DEPARTURE_INFO = 'RECEIVE_DEPARTURE_INFO'
